### ISSUE TITLE
How to watch and run the compiled scripts in /dist?

### ISSUE THREAD

**Issue by coodoo** [jsynowiec/node-flowtype-boilerplate#1]
Since babel:watch will continually output scripts whenever the source changed, just wondering how do you make node to pick up those changes?

**Comment by jsynowiec** [comment]
Hi, thanks for asking.

You have a range of possible solutions. For example:

1. You can use a tool called [nodemon][nodemon] or [node-supervisor][node-supervisor] to watch and reload your compiled code,
2. You can use a more robust version of 1 - a full-fledged process monitor like [pm2][pm2],
3. You can use [babel-node][babel-node] with [nodemon][nodemon] to watch and reload your source without outputting compiled code,
4. You can use a *faster* version of 3 - [babel-watch][babel-watch],

If you want to compile your sources using `babel:watch` command and then reload your application whenever your changes are compiled, use the [nodemon][nodemon]:

1. Install nodemon globally: `npm install -g nodemon`
2. Run your compiled scripts using nodemon: `nodemon . /dist/main.js`

If you *just* want to reload your code on every change, you can skip the compiling and use the [babel-watch][babel-watch] to monitor your source code and "compile in-memory":

1. Install it as a dev dependancy: `yarn add --dev babel-watch` (or `npm install -D babel-watch`)
2. Add a new script to your `package.json` file:
```
  "scripts": {
    "start:dev": "babel-watch dist/main.js"
  }
```
3. Start using `yarn run start:dev` (or `npm run start:dev`)

[nodemon]: https://nodemon.io
[node-supervisor]: https://github.com/petruisfan/node-supervisor
[pm2]: http://pm2.keymetrics.io
[babel-watch]: https://github.com/kmagiera/babel-watch#babel-watch
[babel-node]: https://babeljs.io/docs/usage/cli/#babel-node

**Comment by coodoo** [comment]
Thanks for pointing out to the right direction, `babel-watch` looks like a fantastic solution to the problem, which provides `watch`, `transpilation` and `reload` in one go!
