### ISSUE TITLE
Add support for jsnext:main

### ISSUE THREAD

**Issue by dandv** [jsynowiec/node-flowtype-boilerplate#4]
...and/or pkg.module - see https://github.com/diegohaz/nod/pull/24

**Comment by jsynowiec** [comment]
After reading the explanation in https://github.com/jsforum/jsforum/issues/5 I'm not sure if this should be included in this boilerplate. It's up to the authors to decide whether to include `pkg.module` or not.
Moreover, ES6 code with Flow annotations is not a *valid* ES6. It needs to be processed first (or some on-the-fly loaders are required).
