### ISSUE TITLE
Babel builds only subdirs

### ISSUE THREAD

**Issue by Mottoweb** [jsynowiec/node-flowtype-boilerplate#5]
Specifying `src/**/*.js` builds files only in subdirs.

PR #6

**Comment by Mottoweb** [comment]
#6

**Comment by jsynowiec** [comment]
Works for me - transpiles js files inside of the top src directory.

```
➜ npm run build

> babel src/**/*.js -d dist

src/main.js -> dist/src/main.js
```

**Comment by Mottoweb** [comment]
Worked for me as well until i had a directory lets say, `contollers`, then files inside `controllers` would compile, while no files from `src` would.
